---
title: "oddsRatioCalc"
author: "Patrick Schratz"
date: "3 September 2016"
output: 
  html_document: 
    highlight: textmate
    number_sections: yes
    theme: readable
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```

```{r, echo=FALSE}
calc_oddsratio.gam <- function(data, model, pred, values, factor = NULL,
                          percentage, slice = FALSE, quietly = FALSE) {
  

  names_pred <- colnames(data)
  
  if (slice) {
    
    # get range of pred distribution and slice in x tiles
    range <- max(data[, pred]) - min(data[, pred])
    step <- range / (100/percentage)
    
    range_v <- c()
    
    # create vector of percentage
    for (i in 0:(100/percentage)) {
      range_v <- c(range_v, min(data[, pred]) + step * i)
    }
    
    result <- data.frame(odds_ratio = numeric(length = 100/percentage),
                         from = numeric(length = 100/percentage),
                         to = numeric(length = 100/percentage),
                         perc_from = character(length = 100/percentage),
                         perc_to = character(length = 100/percentage),
                         stringsAsFactors=FALSE)
    
    
    if(!quietly)
      # print variable information
      cat("Predictor: '", pred, "'\nSteps:     ", 100/percentage, " (", percentage, "%)\n", sep="")
    
    # apply OR calc for vector
    for (x in 1:(100/percentage)) {
      
      
      # set all preds to their mean if they are numeric
      for (i in names_pred) {
        if(is.numeric(data[[i]])) 
           data[[i]] <- mean(data[[i]])
      }
      
      # reduce to 1 row
      data <- data[1, ]
      # subset DF to preds only
      data <- data[, names_pred]
      
      # set values[1] of pred
      data[, pred] <- range_v[x]
      # calc log odds for value 1
      pred_gam1 <- as.numeric(predict(model, data, type = "link"))
      # set values[2] of pred
      data[, pred] <- range_v[x+1]
      # calc log odds for value 2
      pred_gam2 <- as.numeric(predict(model, data, type = "link"))
      odds_ratio <- as.numeric(predict(model, data, type = "link"))
      
      
      result$odds_ratio[x] <- as.numeric(exp(pred_gam2 - pred_gam1), 2)
      result$from[x] <- round(range_v[x], 3)
      result$to[x] <-  round(range_v[x+1], 3)
      result$perc_from[x] <- as.character((percentage*x - percentage))
      result$perc_to[x] <- as.character((percentage)*x)

      
      if (!quietly) {
        cat("\nOdds ratio from ", round(range_v[x], 3), "(", 
            (percentage*x - percentage), "%)", " to ", 
            round(range_v[x+1], 3), 
            "(", (percentage)*x, "%): ", 
            as.numeric(exp(pred_gam2 - pred_gam1), 2), sep = "")
      }
    }
    return(result)
  }
  
  # set all preds to their mean if they are numeric
  for (i in names_pred) {
    if(is.numeric(data[[i]]))
       data[[i]] <- mean(data[[i]])
    
  }
  
  # reduce to 1 row
  data <- data[1, ]
  # subset DF to preds only
  data <- data[, names_pred]
  
  # enable to set levels of factor variables manually with a list
  # if (!is.null(factor))
  #   for (i in length(factor)){
  #     df_name <- names(factor)[i]
  #     data[[df_name]] <- factor[[i]]
  #   }
  
  # set values[1] of pred
  data[, pred] <- values[1]
  # calc log odds for value 1
  pred_gam1 <- as.numeric(predict(model, data, type = "link"))
  # set values[2] of pred
  data[, pred] <- values[2]
  # calc log odds for value 2
  pred_gam2 <- as.numeric(predict(model, data, type = "link"))
  
  odds_ratio <- as.numeric(exp(pred_gam2 - pred_gam1), 2)
  value_info <- list(paste0("OR (", values[1], " to ", values[2], ")"))
  
  if (!quietly & !slice)
    # print variable information
    cat("Predictor: '", pred, "'\n", sep = "")
  
  if (!quietly & !slice) {
    cat("\nOdds ratio from ", values[1], " to ",
        values[2], ": ", 
        as.numeric(exp(pred_gam2 - pred_gam1), 2), sep = "" ) 
  }
}

```


# Load example data

Source: help() of predict.gam()

```{r}
suppressPackageStartupMessages(library(mgcv))
n <- 200
sig <- 2
dat <- gamSim(1, n = n,scale = sig)
dat$x4 <- as.factor(ifelse(dat$x0 > median(dat$x0), "A", "B"))

fit_gam <- gam(y ~ s(x0) + s(I(x1^2)) + s(x2) + offset(x3) + x4, data = dat)
```

# Examples

## Calculate OR for specific increment step

```{r}
calc_oddsratio.gam(model = fit_gam, data = dat, pred = "x2",
             values = c(0.099, 0.198))
```


## Calculate OR for increment steps

Slice the training data range in ten pieces and calculate OR between every increment step

```{r}
tmp <- calc_oddsratio.gam(fit_gam, pred = "x2", percentage = 20,
             slice = TRUE, data = dat, quietly = F)
```

