---
title: "oddsRatioCalc"
author: "Patrick Schratz"
date: "3 September 2016"
output: 
  html_document: 
    highlight: textmate
    number_sections: yes
    theme: readable
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```

```{r, echo=FALSE}
oddsratioGAM <- function(model, predictionData, trainingData, steps,
                         predictors = NULL, pred, slice = FALSE,
                         value1, value2) {
  
  # get names of preds
  if (!is.null(predictors)) {
    names_pred <- predictors
  }
  else names_pred <- colnames(predictionData)
  
  if (slice) {
    
    # get range of pred distribution and slice in x tiles
    range <- max(trainingData[, pred]) - min(trainingData[, pred])
    step <- range / steps
    
    range_v <- c()
    # create vector of steps
    for (i in 0:steps) {
      range_v <- c(range_v, min(trainingData[, pred]) + step * i)
    }
    
    result <- data.frame(nrow = 1)
    # apply OR calc for vector
    for (x in 1:(steps)) {
      # set all preds to their mean
      for (i in names_pred) {
        predictionData[[i]] <- mean(predictionData[[i]])
      }
      # reduce to 1 row
      predictionData <- dplyr::slice(predictionData, 1:1)
      # subset DF to preds only
      predictionData <- predictionData[, names_pred]
      
      # set value1 of pred
      predictionData[, pred] <- range_v[x]
      # calc log odds for value 1
      pred_gam1 <- as.numeric(predict(model, predictionData, type = "link"))
      # set value2 of pred
      predictionData[, pred] <- range_v[x+1]
      # calc log odds for value 2
      pred_gam2 <- as.numeric(predict(model, predictionData, type = "link"))
      
      odds_ratio <- as.numeric(exp(pred_gam2 - pred_gam1), 2)
      value_info <- list(paste0("OR (", round(range_v[x], 3), " to ", round(range_v[x+1], 3), ")"))
      
      tmp <- data.frame(odds_ratio)
      names(tmp) <- value_info
      
      result <- cbind(result, tmp)
    }
    result[, 1] <- NULL
    return(result)
  }
  
  # set all preds to their mean
  for (i in names_pred) {
    predictionData[[i]] <- mean(predictionData[[i]])
  }
  
  # reduce to 1 row
  predictionData <- dplyr::slice(predictionData, 1:1)
  # subset DF to preds only
  predictionData <- predictionData[, names_pred]
  
  
  # set value1 of pred
  predictionData[, pred] <- value1
  # calc log odds for value 1
  pred_gam1 <- as.numeric(predict(model, predictionData, type = "link"))
  # set value2 of pred
  predictionData[, pred] <- value2
  # calc log odds for value 2
  pred_gam2 <- as.numeric(predict(model, predictionData, type = "link"))
  
  odds_ratio <- as.numeric(exp(pred_gam2 - pred_gam1), 2)
  value_info <- list(paste0("OR (", value1, " to ", value2, ")"))
  
  # return named array
  array(odds_ratio, dimnames = value_info)
}
```


# Load example data

Source: help() of predict.gam()

```{r}
suppressPackageStartupMessages(library(mgcv))
n <- 200
sig <- 2
dat <- gamSim(1, n = n,scale = sig)

fit_gam <- gam(y ~ s(x0) + s(I(x1^2)) + s(x2) + offset(x3), data = dat)

newdata <- data.frame(x0 = rnorm(30), x1 = rnorm(30), x2 = rnorm(30), x3 = rnorm(30))
```

# Examples

## Calculate OR for specific increment step

```{r}
oddsratioGAM(model = fit_gam, data = dat, pred = "x2",
             values = c(0.099, 0.198))
```


## Calculate OR for increment steps

Slice the training data range in ten pieces and calculate OR between every increment step

```{r}
oddsratioGAM(fit_gam, newdata, pred = "x2", steps = 10, 
             slice = TRUE, trainingData = dat)
```

